title: Maui Puerto Rican Association
subtitle: 1980 - 2024
author:
  name: Nicole Hernandez
  email: nherna51@asu.edu
description:
  Welcome to the first archive dedicated to the Puerto Rican community in Hawaii
url: "https://mshernandez.github.io"
baseurl: "/mpraproject"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  mpraproject: # name of collection
    output: true # makes sure pages are output as html files
    layout: "mpraproject_item" # the layout for the pages to use
    metadata:
      source: "mpraproject.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/mpraproject" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      mpraproject:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - author
          - location
          - title
          - decade
          - object_type
          - current_location 
          - tags
          - ethnographic_note

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Exhibits"
    sub:
      - label: "Photography Collections"
        link: "/collection/"
      - label: "Oral History Collection"
        link: "/exhibits/oralhistory/"
      - label: "Physical Item Collection"
        link: "/exhibits/objects/"
  - label: "Browse"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
  - label: "Contact Us"
    link: "/contact/"

